// Drop-in <img> replacement rendered as <picture> with AVIF + WebP fallback,
// responsive srcSet, explicit dimensions (reserves aspect ratio → no CLS) and a
// JS-free blur-up placeholder (docs/10_PERFORMANCE.md). Images live in
// public/images/ as self-hosted variants generated by scripts/optimize-images.mjs
// — same-origin, no CDN redirects, sized per device. The low-res placeholder is
// painted as the element's CSS background, so the sharp image simply covers it
// once loaded — works without JavaScript.
//
// The <picture> wrapper uses display:contents (`contents`) so the inner <img>
// keeps participating in the parent's layout exactly as a bare <img> would —
// existing sizing/object-fit classes on the image are unaffected.

// Subdirectories are allowed (e.g. /images/vehicles/toyota-zenix-2024.webp) so
// large image families can be foldered; the variant suffix is always appended to
// the full path, matching what scripts/optimize-images.mjs emits.
const LOCAL = /^\/images\/((?:[a-zA-Z0-9-]+\/)*[a-zA-Z0-9-]+)\.webp$/;
const WIDTHS = [480, 768, 1200, 1600];

function localVariants(src) {
  const m = src.match(LOCAL);
  if (!m) return null;
  const name = m[1];
  const srcSet = (ext) =>
    WIDTHS.map((w) => `/images/${name}-${w}.${ext} ${w}w`).join(', ');
  return {
    name,
    avif: srcSet('avif'),
    webp: srcSet('webp'),
    placeholder: `/images/${name}-blur.webp`,
  };
}

export default function OptimizedImage({
  src,
  alt = '',
  width,
  height,
  priority = false,
  sizes = '100vw',
  className = '',
  style,
  ...rest
}) {
  const variants = localVariants(src);

  const img = (
    <img
      src={src}
      srcSet={variants ? variants.webp : undefined}
      sizes={variants ? sizes : undefined}
      alt={alt}
      width={width}
      height={height}
      loading={priority ? 'eager' : 'lazy'}
      fetchpriority={priority ? 'high' : undefined}
      decoding="async"
      className={className}
      style={
        variants
          ? {
              backgroundImage: `url(${variants.placeholder})`,
              backgroundSize: 'cover',
              backgroundPosition: 'center',
              ...style,
            }
          : style
      }
      {...rest}
    />
  );

  if (!variants) return img;

  return (
    <picture className="contents">
      <source type="image/avif" srcSet={variants.avif} sizes={sizes} />
      <source type="image/webp" srcSet={variants.webp} sizes={sizes} />
      {img}
    </picture>
  );
}

/**
 * Build a preload descriptor for a local image — used with <Head> so the
 * browser starts fetching the LCP image before the JS bundle executes. Preloads
 * AVIF (type-gated): browsers without AVIF support ignore the mismatched
 * preload and fetch the WebP <source> normally, so there is no double download.
 */
export function preloadProps(src, sizes = '100vw') {
  const variants = localVariants(src);
  if (!variants) return { href: src };
  return {
    href: `/images/${variants.name}-1200.avif`,
    imageSrcSet: variants.avif,
    imageSizes: sizes,
    type: 'image/avif',
  };
}
