// Drop-in <img> replacement with responsive srcSet, explicit dimensions
// (reduces CLS) and a JS-free blur-up placeholder (docs/10_PERFORMANCE.md).
// Images live in public/images/ as self-hosted WebP variants generated by
// scripts/fetch-images.mjs — same-origin, no CDN redirects, sized per device.
// The low-res placeholder is painted as the element's CSS background, so the
// sharp image simply covers it once loaded — works without JavaScript.

const LOCAL = /^\/images\/([a-zA-Z0-9-]+)\.webp$/;
const WIDTHS = [480, 768, 1200, 1600];

function localVariants(src) {
  const m = src.match(LOCAL);
  if (!m) return null;
  const name = m[1];
  return {
    srcSet: WIDTHS.map((w) => `/images/${name}-${w}.webp ${w}w`).join(', '),
    placeholder: `/images/${name}-blur.webp`,
  };
}

export default function OptimizedImage({
  src,
  alt = '',
  width,
  height,
  priority = false,
  sizes = '100vw',
  className = '',
  style,
  ...rest
}) {
  const variants = localVariants(src);

  return (
    <img
      src={src}
      srcSet={variants?.srcSet}
      sizes={variants ? sizes : undefined}
      alt={alt}
      width={width}
      height={height}
      loading={priority ? 'eager' : 'lazy'}
      fetchpriority={priority ? 'high' : undefined}
      decoding="async"
      className={className}
      style={
        variants
          ? {
              backgroundImage: `url(${variants.placeholder})`,
              backgroundSize: 'cover',
              backgroundPosition: 'center',
              ...style,
            }
          : style
      }
      {...rest}
    />
  );
}

/**
 * Build a preload descriptor for a local image — used with <Head> so the
 * browser starts fetching the LCP image before the JS bundle executes.
 */
export function preloadProps(src, sizes = '100vw') {
  const variants = localVariants(src);
  if (!variants) return { href: src };
  return { href: src, imageSrcSet: variants.srcSet, imageSizes: sizes };
}
